# Generated by Django 3.0.8 on 2021-01-17 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=4, verbose_name='部屋番号')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type_name', models.CharField(max_length=20, verbose_name='部屋タイプ名称')),
            ],
        ),
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.IntegerField(choices=[(1, 'タオル１組'), (2, 'バスタオル'), (3, 'フェイスタオル'), (4, '歯ブラシ'), (5, '貸出物')])),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comp', models.BooleanField(default=False)),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.RoomType'),
        ),
    ]
